# Generated by Django 4.2.5 on 2023-11-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsApp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('respuestaOne', models.CharField(max_length=200)),
                ('respuestaTwo', models.CharField(max_length=200)),
                ('respuestaThree', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
