# Generated by Django 4.2.5 on 2023-11-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsApp2', '0002_preguntas_delete_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntas',
            name='respuestaThree',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='respuestaTwo',
        ),
    ]
